// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/common/Aside/index.vue')['default']
    AsideIndex: typeof import('./src/components/common/Aside/AsideIndex.vue')['default']
    AsidemenuBar: typeof import('./src/components/common/Aside/AsidemenuBar.vue')['default']
    AsideMenubarItem: typeof import('./src/components/common/Aside/AsideMenubarItem.vue')['default']
    AsyncComp: typeof import('./src/components/asyncComp.vue')['default']
    AsyncComp2: typeof import('./src/components/asyncComp2.vue')['default']
    AsyncContainer: typeof import('./src/components/asyncContainer.vue')['default']
    Breadcrumb: typeof import('./src/components/common/Breadcrumb/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    Item: typeof import('./src/components/virtual/Item.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Login: typeof import('./src/components/login.vue')['default']
    Menubar: typeof import('./src/components/common/Aside/menubar.vue')['default']
    Menubaritem: typeof import('./src/components/common/Aside/menubaritem.vue')['default']
    MyItem: typeof import('./src/components/virtual/myItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/common/SvgIcon/index.vue')['default']
    UserItem: typeof import('./src/components/virtual/userItem.vue')['default']
    UseStorage: typeof import('./src/components/useStorage/index.vue')['default']
    Virtual: typeof import('./src/components/virtual/index.vue')['default']
    VirtualList: typeof import('./src/components/virtual/VirtualList.vue')['default']
  }
}

export {}
