// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaGua: typeof import('./src/components/baGua/baGua.vue')['default']
    Drag: typeof import('./src/components/upload/drag.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    InfiniteScroll: typeof import('./src/components/InfiniteScroll/index.vue')['default']
    JianCaiUpload: typeof import('./src/components/jianCaiUpload/index.vue')['default']
    Loading: typeof import('./src/components/loading/index.vue')['default']
    LoadingPage: typeof import('./src/components/loading/loadingPage.vue')['default']
    Magnifers: typeof import('./src/components/magnifiers/magnifers.vue')['default']
    Magnifiers: typeof import('./src/components/magnifiers/index.vue')['default']
    PreviewImage: typeof import('./src/components/previewImage/index.vue')['default']
    ReverseCard: typeof import('./src/components/reverse-card/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Upload: typeof import('./src/components/upload/index.vue')['default']
    UserItem: typeof import('./src/components/virtual/userItem.vue')['default']
    UseStorage: typeof import('./src/components/useStorage/index.vue')['default']
    Virtual: typeof import('./src/components/virtual/index.vue')['default']
    VirtualList: typeof import('./src/components/virtual/VirtualList.vue')['default']
  }
}

export {}
