// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/common/Aside/index.vue')['default']
    AsyncComp: typeof import('./src/components/asyncComp.vue')['default']
    AsyncComp2: typeof import('./src/components/asyncComp2.vue')['default']
    AsyncConatainer: typeof import('./src/components/asyncConatainer.vue')['default']
    AsyncContainer: typeof import('./src/components/asyncContainer.vue')['default']
    Breadcrumb: typeof import('./src/components/common/Breadcrumb/index.vue')['default']
    ElAside: typeof import('element-plus/es/el-aside')['default']
    ElBreadcrumb: typeof import('element-plus/es/el-breadcrumb')['default']
    ElBreadcrumbItem: typeof import('element-plus/es/el-breadcrumb-item')['default']
    ElButton: typeof import('element-plus/es/el-button')['default']
    ElCheckbox: typeof import('element-plus/es/el-checkbox')['default']
    ElCheckboxGroup: typeof import('element-plus/es/el-checkbox-group')['default']
    ElCol: typeof import('element-plus/es/el-col')['default']
    ElContainer: typeof import('element-plus/es/el-container')['default']
    ElDatePicker: typeof import('element-plus/es/el-date-picker')['default']
    ElDrawer: typeof import('element-plus/es/el-drawer')['default']
    ElDropdown: typeof import('element-plus/es/el-dropdown')['default']
    ElDropdownItem: typeof import('element-plus/es/el-dropdown-item')['default']
    ElDropdownMenu: typeof import('element-plus/es/el-dropdown-menu')['default']
    ElForm: typeof import('element-plus/es/el-form')['default']
    ElFormItem: typeof import('element-plus/es/el-form-item')['default']
    ElHeader: typeof import('element-plus/es/el-header')['default']
    ElIcon: typeof import('element-plus/es/el-icon')['default']
    ElIconSetting: typeof import('element-plus/es/el-icon-setting')['default']
    ElInput: typeof import('element-plus/es/el-input')['default']
    ElMain: typeof import('element-plus/es/el-main')['default']
    ElMenu: typeof import('element-plus/es/el-menu')['default']
    ElMenuItem: typeof import('element-plus/es/el-menu-item')['default']
    ElMenuItemGroup: typeof import('element-plus/es/el-menu-item-group')['default']
    ElOption: typeof import('element-plus/es/el-option')['default']
    ElRadio: typeof import('element-plus/es/el-radio')['default']
    ElRadioGroup: typeof import('element-plus/es/el-radio-group')['default']
    ElSelect: typeof import('element-plus/es/el-select')['default']
    ElSubmenu: typeof import('element-plus/es/el-submenu')['default']
    ElSubMenu: typeof import('element-plus/es/el-sub-menu')['default']
    ElSwitch: typeof import('element-plus/es/el-switch')['default']
    ElTable: typeof import('element-plus/es/el-table')['default']
    ElTableColumn: typeof import('element-plus/es/el-table-column')['default']
    ElTimePicker: typeof import('element-plus/es/el-time-picker')['default']
    Layout: typeof import('./src/components/layout.vue')['default']
    Login: typeof import('./src/components/login.vue')['default']
    Login2: typeof import('./src/components/login2.vue')['default']
    SvgIcon: typeof import('./src/components/common/SvgIcon/index.vue')['default']
  }
}

export { }
